[package]
name = "qubit-tokio-executor"
version = "0.9.0"
publish = false
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-tokio-executor"
description = "Tokio-backed executor and executor service implementations for Qubit Rust libraries"
homepage = "https://github.com/qubit-ltd/rs-tokio-executor"
documentation = "https://docs.rs/qubit-tokio-executor"
readme = "README.md"
keywords = ["tokio", "executor", "async", "concurrency"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_tokio_executor"
doctest = true

[dependencies]
tokio = { version = "1.52", features = ["rt", "sync"] }

parking_lot = "0.12"
qubit-dcl = "0.12"
qubit-atomic = "0.13"
qubit-function = "0.16"
qubit-executor = { version = "0.8", path = "../rs-executor" }
qubit-lock = { default-features = false, features = ["monitor", "parking-lot"], version = "0.13" }

[dev-dependencies]
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "time"] }
